/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "VoxelSniper"

pluginManagement {
    repositories {
        gradlePluginPortal()
//        maven("https://papermc.io/repo/repository/maven-public/")
    }
}

include("VoxelSniperCore")
include("VoxelSniperSpigot")