name: ${projectName}
main: com.github.kevindagame.voxelsniper.SpigotVoxelSniper
version: ${version}
api-version: 1.15
website: https://github.com/KevinDaGame/VoxelSniper-Reimagined
authors: [przerwap, MikeMatrix, Gavjenks, giltwist, psanker, Deamon5550, DivineRage, KevDaDev, Lennart99]
description: The premier long-distance brush editor for Minecraft, reimagined!
softdepend: [VoxelModPackPlugin]
commands:
  u:
    description: Undo changes made by yourself or other players.
    permission: voxelsniper.sniper
    aliases: [undo]
    usage: Invalid syntax. Use /<command> help to see valid syntax.
  uu:
    description: Undo changes made by other players.
    permission: voxelsniper.sniper
    aliases: [undouser]
    usage: Invalid syntax. Use /<command> help to see valid syntax.
  d:
    description: Reverts all values back to defaults.
    permission: voxelsniper.sniper
    alias: [default]
    usage: Invalid syntax. Use /<command> help to see valid syntax.
  p:
    description: Change the currently active performer for the performer brush.
    permission: voxelsniper.sniper
    aliases: [perf, performer]
    usage: Invalid syntax. Use /<command> help to see valid syntax.
  sniper:
    description: View and change settings related to VoxelSniper.
    permission: voxelsniper.sniper
    aliases: [voxelsniper, vs]
    usage: Invalid syntax. Use /<command> help to see valid syntax.
  vi:
    description: Changes the data value of the currently active voxel material.
    permission: voxelsniper.sniper
    usage: Invalid syntax. Use /<command> help to see valid syntax.
  vir:
    description: Changes the data value of the currently active replace material.
    permission: voxelsniper.sniper
    usage: Invalid syntax. Use /<command> help to see valid syntax.
  v:
    description: Changes the currently active voxel material.
    permission: voxelsniper.sniper
    usage: Invalid syntax. Use /<command> help to see valid syntax.
  vr:
    description: Changes the currently active replace material.
    permission: voxelsniper.sniper
    usage: Invalid syntax. Use /<command> help to see valid syntax.
  b:
    description: Brush.
    permission: voxelsniper.sniper
    usage: Invalid syntax. Use /<command> help to see valid syntax.
  btool:
    description: Command to assign brush tools to custom items.
    permission: voxelsniper.sniper
    usage: Invalid syntax. Use /<command> help to see valid syntax.
  vox:
    description: Multi-purpose command to perform various utility functions.
    permission: voxelsniper.sniper
    aliases: [painting, vchunk, goto]
    usage: Invalid syntax. Use /<command> help to see valid syntax.
  vv:
    description: Changes various variables related to voxel brushes.
    permission: voxelsniper.sniper
    aliases: [vl, vc, vh, vvariables, vvar, variables]
    usage: Invalid syntax. Use /<command> help to see valid syntax.
permissions:
  voxelsniper.*:
    description: Allows access to all VoxelSniper commands.
    children:
      voxelsniper.sniper:
        description: Allows acces to snipe commands
      voxelsniper.ignorelimitations:
        description: Allows player to ignore brush limitations
      voxelsniper.goto:
        description: Allows player to use the goto command
      voxelsniper.undouser:
        description: Allows player to use the undouser command
      voxelsniper.brush.*:
        description: Allows player to use all brushes
        children:
          voxelsniper.brush.ball: true
          voxelsniper.brush.biome: true
          voxelsniper.brush.blendball: true
          voxelsniper.brush.blenddisc: true
          voxelsniper.brush.blendvoxel: true
          voxelsniper.brush.blendvoxeldisc: true
          voxelsniper.brush.blob: true
          voxelsniper.brush.blockreset: true
          voxelsniper.brush.blockresetsurface: true
          voxelsniper.brush.canyon: true
          voxelsniper.brush.canyonselection: true
          voxelsniper.brush.checkervoxeldisc: true
          voxelsniper.brush.cleansnow: true
          voxelsniper.brush.clonestamp: true
          voxelsniper.brush.comet: true
          voxelsniper.brush.copypasta: true
          voxelsniper.brush.cylinder: true
          voxelsniper.brush.disc: true
          voxelsniper.brush.discface: true
          voxelsniper.brush.dome: true
          voxelsniper.brush.drain: true
          voxelsniper.brush.ellipse: true
          voxelsniper.brush.ellipsoid: true
          voxelsniper.brush.entity: true
          voxelsniper.brush.entityremoval: true
          voxelsniper.brush.eraser: true
          voxelsniper.brush.erode: true
          voxelsniper.brush.extrude: true
          voxelsniper.brush.filldown: true
          voxelsniper.brush.flatocean: true
          voxelsniper.brush.generatetree: true
          voxelsniper.brush.heatray: true
          voxelsniper.brush.jaggedline: true
          voxelsniper.brush.jockey: true
          voxelsniper.brush.lightning: true
          voxelsniper.brush.line: true
          voxelsniper.brush.move: true
          voxelsniper.brush.ocean: true
          voxelsniper.brush.overlay: true
          voxelsniper.brush.painting: true
          voxelsniper.brush.pull: true
          voxelsniper.brush.punish: true
          voxelsniper.brush.randomerode: true
          voxelsniper.brush.regeneratechunk: true
          voxelsniper.brush.ring: true
          voxelsniper.brush.rot2d: true
          voxelsniper.brush.rot2dvert: true
          voxelsniper.brush.rot3d: true
          voxelsniper.brush.ruler: true
          voxelsniper.brush.scanner: true
          voxelsniper.brush.set: true
          voxelsniper.brush.setredstoneflip: true
          voxelsniper.brush.setredstonerotate: true
          voxelsniper.brush.shellball: true
          voxelsniper.brush.shellset: true
          voxelsniper.brush.shellvoxel: true
          voxelsniper.brush.signoverwrite: true
          voxelsniper.brush.snipe: true
          voxelsniper.brush.snowcone: true
          voxelsniper.brush.spiralstaircase: true
          voxelsniper.brush.splatterball: true
          voxelsniper.brush.splatterdisc: true
          voxelsniper.brush.splatteroverlay: true
          voxelsniper.brush.splattervoxel: true
          voxelsniper.brush.splattervoxeldisc: true
          voxelsniper.brush.spline: true
          voxelsniper.brush.stamp: true
          voxelsniper.brush.stencil: true
          voxelsniper.brush.stencillist: true
          voxelsniper.brush.threepointcircle: true
          voxelsniper.brush.treesnipe: true
          voxelsniper.brush.triangle: true
          voxelsniper.brush.underlay: true
          voxelsniper.brush.voltmeter: true
          voxelsniper.brush.voxel: true
          voxelsniper.brush.voxeldisc: true
          voxelsniper.brush.voxeldiscface: true
          voxelsniper.brush.warp: true
      voxelsniper.brush.ball:
        default: op
      voxelsniper.brush.biome:
        default: op
      voxelsniper.brush.blendball:
        default: op
      voxelsniper.brush.blenddisc:
        default: op
      voxelsniper.brush.blendvoxel:
        default: op
      voxelsniper.brush.blendvoxeldisc:
        default: op
      voxelsniper.brush.blob:
        default: op
      voxelsniper.brush.blockreset:
        default: op
      voxelsniper.brush.blockresetsurface:
        default: op
      voxelsniper.brush.canyon:
        default: op
      voxelsniper.brush.canyonselection:
        default: op
      voxelsniper.brush.checkervoxeldisc:
        default: op
      voxelsniper.brush.cleansnow:
        default: op
      voxelsniper.brush.clonestamp:
        default: op
      voxelsniper.brush.comet:
        default: op
      voxelsniper.brush.copypasta:
        default: op
      voxelsniper.brush.cylinder:
        default: op
      voxelsniper.brush.disc:
        default: op
      voxelsniper.brush.discface:
        default: op
      voxelsniper.brush.dome:
        default: op
      voxelsniper.brush.drain:
        default: op
      voxelsniper.brush.ellipse:
        default: op
      voxelsniper.brush.ellipsoid:
        default: op
      voxelsniper.brush.entity:
        default: op
      voxelsniper.brush.entityremoval:
        default: op
      voxelsniper.brush.eraser:
        default: op
      voxelsniper.brush.erode:
        default: op
      voxelsniper.brush.extrude:
        default: op
      voxelsniper.brush.filldown:
        default: op
      voxelsniper.brush.flatocean:
        default: op
      voxelsniper.brush.generatetree:
        default: op
      voxelsniper.brush.heatray:
        default: op
      voxelsniper.brush.jaggedline:
        default: op
      voxelsniper.brush.jockey:
        default: op
      voxelsniper.brush.lightning:
        default: op
      voxelsniper.brush.line:
        default: op
      voxelsniper.brush.move:
        default: op
      voxelsniper.brush.ocean:
        default: op
      voxelsniper.brush.overlay:
        default: op
      voxelsniper.brush.painting:
        default: op
      voxelsniper.brush.pull:
        default: op
      voxelsniper.brush.punish:
        default: op
      voxelsniper.brush.randomerode:
        default: op
      voxelsniper.brush.regeneratechunk:
        default: op
      voxelsniper.brush.ring:
        default: op
      voxelsniper.brush.rot2d:
        default: op
      voxelsniper.brush.rot2dvert:
        default: op
      voxelsniper.brush.rot3d:
        default: op
      voxelsniper.brush.ruler:
        default: op
      voxelsniper.brush.scanner:
        default: op
      voxelsniper.brush.set:
        default: op
      voxelsniper.brush.setredstoneflip:
        default: op
      voxelsniper.brush.setredstonerotate:
        default: op
      voxelsniper.brush.shellball:
        default: op
      voxelsniper.brush.shellset:
        default: op
      voxelsniper.brush.shellvoxel:
        default: op
      voxelsniper.brush.signoverwrite:
        default: op
      voxelsniper.brush.snipe:
        default: op
      voxelsniper.brush.snowcone:
        default: op
      voxelsniper.brush.spiralstaircase:
        default: op
      voxelsniper.brush.splatterball:
        default: op
      voxelsniper.brush.splatterdisc:
        default: op
      voxelsniper.brush.splatteroverlay:
        default: op
      voxelsniper.brush.splattervoxel:
        default: op
      voxelsniper.brush.splattervoxeldisc:
        default: op
      voxelsniper.brush.spline:
        default: op
      voxelsniper.brush.stamp:
        default: op
      voxelsniper.brush.stencil:
        default: op
      voxelsniper.brush.stencillist:
        default: op
      voxelsniper.brush.threepointcircle:
        default: op
      voxelsniper.brush.treesnipe:
        default: op
      voxelsniper.brush.triangle:
        default: op
      voxelsniper.brush.underlay:
        default: op
      voxelsniper.brush.voltmeter:
        default: op
      voxelsniper.brush.voxel:
        default: op
      voxelsniper.brush.voxeldisc:
        default: op
      voxelsniper.brush.voxeldiscface:
        default: op
      voxelsniper.brush.warp:
        default: op
